# Generated by Django 2.0.2 on 2018-06-04 03:14

from django.db import migrations, models
import django.db.models.deletion
import exercises.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Titulo')),
                ('date_delivery', models.DateTimeField(verbose_name='Fecha de entrega')),
                ('url', models.FileField(upload_to='Exercises', validators=[exercises.validators.validate_file_extension], verbose_name='Url')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'Ejecicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Group1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='NombreGrupo')),
                ('alumn', models.ManyToManyField(blank=True, to='registration.Alumn', verbose_name='Alumnos')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Teacher', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Group1', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Teacher', verbose_name='Autor'),
        ),
    ]
